### PR TITLE
Default to publishing single file

### PR DESCRIPTION
**Pull request by Raicuparta**

### CODE REVIEW

**Comment by praydog** [comment]
Almost there, but looks like some random DLLs are in there still compared to a local VS publish

**Comment by Raicuparta** [comment]
yeah no idea what those are, was just doing a quick test since I'm not on Windows right now, will look further into it a bit

**Comment by Raicuparta** [comment]
Alright, there you go :) Took me a few attempts to make it not default to self-contained.

Self-contained means it bundles the entire .NET runtime (making the final build way bigger), and apparently also added some extra dlls. This is useful if you don't want users to have to install the runtime themselves, but probably worth it since Windows already gives helpful errors in that case. So I made it not self-contained.

PublishSingleFile is what actually makes it put all the dlls into the main exe.

**Comment by Raicuparta** [comment]
btw @praydog do you wanna get rid of the pdb and .config files in the release builds? That's pretty easy to do as well.

**Comment by praydog** [comment]
Hmm, I don't want to do this for the backend, so not sure why I'd want to do it for the frontend. Though there is no crash logging, or any logging at all set up so it makes no sense for the frontend. At least for the backend, if I get a proper commit hash I can pull the PDB from the nightlies and properly analyze the dumps.

**Review by praydog — APPROVED** [review]
works on my machine

**Comment by praydog** [comment]
After thinking about it, yeah I'm okay with having those files removed - at least for the frontend. The less space occupied the better, if it's not necessary or useful to have the PDB for the frontend there. And at least for actions I believe they count towards my storage limit.

**Pull request merged**
